[package]
name = "source2-kv3"
description = "Reader for Valve's binary KeyValues 3 (KV3)"
keywords = ["source2", "kv3", "keyvalues", "valve"]
categories = ["game-development", "parser-implementations"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"

[dependencies]
lz4_flex = { workspace = true, optional = true }
ruzstd = { workspace = true, optional = true }

[features]
default = ["lz4", "zstd"]
lz4 = ["dep:lz4_flex"]
zstd = ["dep:ruzstd"]

[lints]
workspace = true
